### ISSUE TITLE
Upgrade org.freedesktop.Sdk.Extension.golang to 24.08

### ISSUE THREAD

**Issue by klugier** [flathub/org.freedesktop.Sdk.Extension.golang#110] opened 2024-09-14 10:51 UTC
Please create golang SDK extension to 24.08. Since it is dependency to my application github.com/flathub/org.ultimatepp.TheIDE. I can not upgrade it to 24.08 since new golang dependency will have support for this version.

Links:
- https://github.com/flathub/org.freedesktop.Sdk.Extension.golang
- https://github.com/flathub/org.ultimatepp.TheIDE (My published application TheIDE that is basing on golang SDK)

**Comment by bbhtt** [comment] 2024-09-14 12:31
Duplicate of https://github.com/flathub/org.freedesktop.Sdk.Extension.golang/issues/109

**Closed as not planned by bbhtt** 2024-09-14 12:31 UTC
